FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV API_HOST=0.0.0.0
ENV API_PORT=8000

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY data ./data
COPY src ./src

EXPOSE 8000

CMD ["uvicorn", "src.api.company_locations_api:app", "--host", "0.0.0.0", "--port", "8000"]
